package io.macrosquare.execution.domain.service;

import io.macrosquare.execution.domain.model.PurchasingPowerProjection;
import io.macrosquare.execution.domain.model.PurchasingPowerProjection.PurchasingPowerScenario;

import java.util.List;

/**
 * Pure domain policy for nominal compounding and real purchasing power.
 *
 * <p>This policy intentionally does not infer an expected market return from
 * recent performance. The productive-asset return is an explicit user scenario,
 * not a forecast generated by the system.</p>
 */
public final class PurchasingPowerPolicy {

    public static final String METHODOLOGY =
            "명목 미래가치=P×(1+r)^n, 오늘 가치 기준 실질 미래가치=명목 미래가치÷(1+물가상승률)^n, "
                    + "연 실질수익률=(1+r)÷(1+물가상승률)-1. 세금·수수료·변동성·손실 순서는 제외한 교육용 시나리오입니다.";

    public PurchasingPowerProjection evaluate(
            long principalKrw,
            int years,
            double inflationPct,
            double cashYieldPct,
            double productiveAssetReturnPct
    ) {
        validate(principalKrw, years, inflationPct, cashYieldPct, productiveAssetReturnPct);
        var inflation = inflationPct / 100.0;
        var futureBasketCost = roundKrw(principalKrw * compound(inflation, years));
        var cash = scenario(
                "CASH_LIKE", "예금·현금성", principalKrw, years, inflation, cashYieldPct);
        var productiveAsset = scenario(
                "PRODUCTIVE_ASSET", "생산자산 가정", principalKrw, years, inflation,
                productiveAssetReturnPct);
        var advantage = productiveAsset.realFutureValueKrw() - cash.realFutureValueKrw();
        var summary = cash.annualRealReturnPct() < 0
                ? "예금 금리가 물가보다 낮아 명목 잔액이 늘어도 실질 구매력은 감소합니다."
                : "예금 금리가 물가를 웃돌아 현금성 자산의 실질 구매력이 유지되는 가정입니다.";
        return new PurchasingPowerProjection(
                principalKrw,
                years,
                round2(inflationPct),
                futureBasketCost,
                cash,
                productiveAsset,
                advantage,
                summary,
                METHODOLOGY,
                List.of(
                        "생산자산 수익률은 예측값이 아니라 직접 바꾸는 가정입니다.",
                        "장기 평균수익률이 같아도 큰 초기 손실과 인출 시점에 따라 실제 결과는 달라집니다.",
                        "투자 가능 구간·기업 건강도·밸류·분할매수 적격성 판단은 별도 신호로 확인해야 합니다."
                )
        );
    }

    private static PurchasingPowerScenario scenario(
            String key,
            String label,
            long principalKrw,
            int years,
            double inflation,
            double nominalReturnPct
    ) {
        var nominalReturn = nominalReturnPct / 100.0;
        var nominal = roundKrw(principalKrw * compound(nominalReturn, years));
        var real = roundKrw(nominal / compound(inflation, years));
        var realAnnualReturn = ((1 + nominalReturn) / (1 + inflation) - 1) * 100;
        var retention = real * 100.0 / principalKrw;
        return new PurchasingPowerScenario(
                key,
                label,
                round2(nominalReturnPct),
                round2(realAnnualReturn),
                nominal,
                real,
                round1(retention),
                real - principalKrw
        );
    }

    private static void validate(
            long principalKrw,
            int years,
            double inflationPct,
            double cashYieldPct,
            double productiveAssetReturnPct
    ) {
        if (principalKrw < 1 || principalKrw > 10_000_000_000_000L) {
            throw new IllegalArgumentException("principalKrw must be between 1 and 10 trillion");
        }
        if (years < 1 || years > 100) {
            throw new IllegalArgumentException("years must be between 1 and 100");
        }
        validateRate(inflationPct, "inflationPct");
        validateRate(cashYieldPct, "cashYieldPct");
        validateRate(productiveAssetReturnPct, "productiveAssetReturnPct");
    }

    private static void validateRate(double value, String field) {
        if (!Double.isFinite(value) || value <= -99 || value > 200) {
            throw new IllegalArgumentException(field + " must be finite and between -99 and 200");
        }
    }

    private static double compound(double annualRate, int years) {
        var value = Math.pow(1 + annualRate, years);
        if (!Double.isFinite(value) || value < 0) {
            throw new IllegalArgumentException("scenario exceeds supported numeric range");
        }
        return value;
    }

    private static long roundKrw(double value) {
        if (!Double.isFinite(value) || value < 0 || value > Long.MAX_VALUE) {
            throw new IllegalArgumentException("future value exceeds supported KRW range");
        }
        return Math.round(value);
    }

    private static double round1(double value) {
        return Math.round(value * 10.0) / 10.0;
    }

    private static double round2(double value) {
        return Math.round(value * 100.0) / 100.0;
    }
}
